version: '3'

services:
  redis:
    hostname: redis
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data